version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/test
permissions:
  - object: /home/ec2-user/test
    pattern: "**"
    owner: root
    mode: 777
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: root