spring:
  profiles:
    group:
      local: "localdb,common"
      server: "serverdb,common"
    active: local
logging:
  level:
    root: info

---

spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root

---

spring:
  config:
    import: classpath:/localkey.yml
    activate:
      on-profile: localdb
  datasource:
    url: jdbc:mariadb://localhost:3306/study
    password: 1234
slack:
  token: ${localkey.slack.token}

---

spring:
  config:
    activate:
      on-profile: serverdb
  datasource:
    url: ${test.mariadb.url}
    password: ${test.mariadb.password}
slack:
  token: ${test.slack.token}