spring:
  profiles:
    group:
      local: "localdb,common"
      server: "serverdb,common"
    active: local

---

spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

---

spring:
  config:
    activate:
      on-profile: localdb
  datasource:
    url: jdbc:mariadb://localhost:3306/study
    username: root
    password: 1234

---

spring:
  config:
    activate:
      on-profile: serverdb
  datasource:
    url: ${test.mariadb.url}
    username: ${test.mariadb.username}
    password: ${test.mariadb.password}